export const COLORS = [
  {colorName: 'Alice Blue', hexCode: '#F0F8FF', isShown: true},
  {colorName: 'Antique White', hexCode: '#FAEBD7', isShown: false},
  {colorName: 'Aqua', hexCode: '#00FFFF', isShown: false},
  {colorName: 'Aquamarine', hexCode: '#7FFFD4', isShown: true},
  {colorName: 'Azure', hexCode: '#F0FFFF', isShown: true},
  {colorName: 'Beige', hexCode: '#F5F5DC', isShown: true},
  {colorName: 'Bisque', hexCode: '#FFE4C4', isShown: true},
  {colorName: 'Black', hexCode: '#000000', isShown: false},
  {colorName: 'Blanched Almond', hexCode: '#FFEBCD', isShown: true},
  {colorName: 'Blue', hexCode: '#0000FF', isShown: false},
  {colorName: 'Blue Violet', hexCode: '#8A2BE2', isShown: true},
  {colorName: 'Brown', hexCode: '#A52A2A', isShown: false},
  {colorName: 'Burly Wood', hexCode: '#DEB887', isShown: true},
  {colorName: 'Cadet Blue', hexCode: '#5F9EA0', isShown: true},
  {colorName: 'Chartreuse', hexCode: '#7FFF00', isShown: false},
  {colorName: 'Chocolate', hexCode: '#D2691E', isShown: true},
  {colorName: 'Coral', hexCode: '#FF7F50', isShown: false},
  {colorName: 'Cornflower Blue', hexCode: '#6495ED', isShown: true},
  {colorName: 'Cornsilk', hexCode: '#FFF8DC', isShown: true},
  {colorName: 'Crimson', hexCode: '#DC143C', isShown: false},
  {colorName: 'Cyan', hexCode: '#00FFFF', isShown: false},
  {colorName: 'Dark Blue', hexCode: '#00008B', isShown: false},
  {colorName: 'Dark Cyan', hexCode: '#008B8B', isShown: true},
  {colorName: 'Dark Golden Rod', hexCode: '#B8860B', isShown: true},
  {colorName: 'Dark Gray', hexCode: '#A9A9A9', isShown: false},
  {colorName: 'Dark Grey', hexCode: '#A9A9A9', isShown: false},
  {colorName: 'Dark Green', hexCode: '#006400', isShown: false},
  {colorName: 'Dark Khaki', hexCode: '#BDB76B', isShown: false},
  {colorName: 'Dark Magenta', hexCode: '#8B008B', isShown: false},
  {colorName: 'Dark Olive Green', hexCode: '#556B2F', isShown: false},
  {colorName: 'Dark Orange', hexCode: '#FF8C00', isShown: false},
  {colorName: 'Dark Orchid', hexCode: '#9932CC', isShown: false},
  {colorName: 'Dark Red', hexCode: '#8B0000', isShown: false},
  {colorName: 'Dark Salmon', hexCode: '#E9967A', isShown: false},
  {colorName: 'Dark Sea Green', hexCode: '#8FBC8F', isShown: false},
  {colorName: 'Dark Slate Blue', hexCode: '#483D8B', isShown: true},
  {colorName: 'Dark Slate Gray', hexCode: '#2F4F4F', isShown: false},
  {colorName: 'Dark Slate Grey', hexCode: '#2F4F4F', isShown: false},
  {colorName: 'Dark Turquoise', hexCode: '#00CED1', isShown: false},
  {colorName: 'Dark Violet', hexCode: '#9400D3', isShown: false},
  {colorName: 'Deep Pink', hexCode: '#FF1493', isShown: false},
  {colorName: 'Deep Sky Blue', hexCode: '#00BFFF', isShown: false},
  {colorName: 'Dim Gray', hexCode: '#696969', isShown: true},
  {colorName: 'Dodger Blue', hexCode: '#1E90FF', isShown: false},
  {colorName: 'Fire Brick', hexCode: '#B22222', isShown: false},
  {colorName: 'Floral White', hexCode: '#FFFAF0', isShown: false},
  {colorName: 'Forest Green', hexCode: '#228B22', isShown: false},
  {colorName: 'Fuchsia', hexCode: '#FF00FF', isShown: false},
  {colorName: 'Gainsboro', hexCode: '#DCDCDC', isShown: false},
  {colorName: 'Ghost White', hexCode: '#F8F8FF', isShown: false},
  {colorName: 'Gold', hexCode: '#FFD700', isShown: true},
  {colorName: 'Golden Rod', hexCode: '#DAA520', isShown: true},
  {colorName: 'Gray', hexCode: '#808080', isShown: false},
  {colorName: 'Green', hexCode: '#008000', isShown: true},
  {colorName: 'Green Yellow', hexCode: '#ADFF2F', isShown: false},
  {colorName: 'Honey Dew', hexCode: '#F0FFF0', isShown: false},
  {colorName: 'Hot Pink', hexCode: '#FF69B4', isShown: true},
  {colorName: 'Indian Red', hexCode: '#CD5C5C', isShown: true},
  {colorName: 'Indigo', hexCode: '#4B0082', isShown: false},
  {colorName: 'Ivory', hexCode: '#FFFFF0', isShown: false},
  {colorName: 'Khaki', hexCode: '#F0E68C', isShown: false},
  {colorName: 'Lavender', hexCode: '#E6E6FA', isShown: false},
  {colorName: 'Lavender Blush', hexCode: '#FFF0F5', isShown: false},
  {colorName: 'Lawn Green', hexCode: '#7CFC00', isShown: false},
  {colorName: 'Lemon Chiffon', hexCode: '#FFFACD', isShown: false},
  {colorName: 'Light Blue', hexCode: '#ADD8E6', isShown: false},
  {colorName: 'Light Coral', hexCode: '#F08080', isShown: true},
  {colorName: 'Light Cyan', hexCode: '#E0FFFF', isShown: false},
  {colorName: 'Light Golden Rod Yellow', hexCode: '#FAFAD2', isShown: false},
  {colorName: 'Light Gray', hexCode: '#D3D3D3', isShown: false},
  {colorName: 'Light Grey', hexCode: '#D3D3D3', isShown: false},
  {colorName: 'Light Green', hexCode: '#90EE90', isShown: false},
  {colorName: 'Light Pink', hexCode: '#FFB6C1', isShown: true},
  {colorName: 'Light Salmon', hexCode: '#FFA07A', isShown: false},
  {colorName: 'Light Sea Green', hexCode: '#20B2AA', isShown: true},
  {colorName: 'Light Sky Blue', hexCode: '#87CEFA', isShown: false},
  {colorName: 'Light Slate Gray', hexCode: '#778899', isShown: true},
  {colorName: 'Light Slate Grey', hexCode: '#778899', isShown: false},
  {colorName: 'Light Steel Blue', hexCode: '#B0C4DE', isShown: false},
  {colorName: 'Light Yellow', hexCode: '#FFFFE0', isShown: false},
  {colorName: 'Lime', hexCode: '#00FF00', isShown: false},
  {colorName: 'Lime Green', hexCode: '#32CD32', isShown: false},
  {colorName: 'Linen', hexCode: '#FAF0E6', isShown: false},
  {colorName: 'Magenta', hexCode: '#FF00FF', isShown: false},
  {colorName: 'Maroon', hexCode: '#800000', isShown: false},
  {colorName: 'Medium Aqua Marine', hexCode: '#66CDAA', isShown: false},
  {colorName: 'Medium Blue', hexCode: '#0000CD', isShown: false},
  {colorName: 'Medium Orchid', hexCode: '#BA55D3', isShown: false},
  {colorName: 'Medium Purple', hexCode: '#9370D8', isShown: true},
  {colorName: 'Medium Sea Green', hexCode: '#3CB371', isShown: true},
  {colorName: 'Medium Slate Blue', hexCode: '#7B68EE', isShown: true},
  {colorName: 'Medium Spring Green', hexCode: '#00FA9A', isShown: false},
  {colorName: 'Medium Turquoise', hexCode: '#48D1CC', isShown: true},
  {colorName: 'Medium Violet Red', hexCode: '#C71585', isShown: true},
  {colorName: 'Midnight Blue', hexCode: '#191970', isShown: false},
  {colorName: 'Mint Cream', hexCode: '#F5FFFA', isShown: false},
  {colorName: 'MistyRose', hexCode: '#FFE4E1', isShown: false},
  {colorName: 'Moccasin', hexCode: '#FFE4B5', isShown: false},
  {colorName: 'Navajo White', hexCode: '#FFDEAD', isShown: false},
  {colorName: 'Navy', hexCode: '#000080', isShown: false},
  {colorName: 'OldLace', hexCode: '#FDF5E6', isShown: false},
  {colorName: 'Olive', hexCode: '#808000', isShown: false},
  {colorName: 'Olive Drab', hexCode: '#6B8E23', isShown: false},
  {colorName: 'Orange', hexCode: '#FFA500', isShown: false},
  {colorName: 'Orange Red', hexCode: '#FF4500', isShown: false},
  {colorName: 'Orchid', hexCode: '#DA70D6', isShown: false},
  {colorName: 'Pale Golden Rod', hexCode: '#EEE8AA', isShown: false},
  {colorName: 'Pale Green', hexCode: '#98FB98', isShown: false},
  {colorName: 'Pale Turquoise', hexCode: '#AFEEEE', isShown: false},
  {colorName: 'Pale Violet Red', hexCode: '#D87093', isShown: false},
  {colorName: 'Papaya Whip', hexCode: '#FFEFD5', isShown: false},
  {colorName: 'Peach Puff', hexCode: '#FFDAB9', isShown: false},
  {colorName: 'Peru', hexCode: '#CD853F', isShown: true},
  {colorName: 'Pink', hexCode: '#FFC0CB', isShown: true},
  {colorName: 'Plum', hexCode: '#DDA0DD', isShown: true},
  {colorName: 'Powder Blue', hexCode: '#B0E0E6', isShown: false},
  {colorName: 'Purple', hexCode: '#800080', isShown: false},
  {colorName: 'Red', hexCode: '#FF0000', isShown: false},
  {colorName: 'Rosy Brown', hexCode: '#BC8F8F', isShown: false},
  {colorName: 'Royal Blue', hexCode: '#4169E1', isShown: false},
  {colorName: 'Saddle Brown', hexCode: '#8B4513', isShown: false},
  {colorName: 'Salmon', hexCode: '#FA8072', isShown: false},
  {colorName: 'Sandy Brown', hexCode: '#F4A460', isShown: false},
  {colorName: 'Sea Green', hexCode: '#2E8B57', isShown: false},
  {colorName: 'SeaShell', hexCode: '#FFF5EE', isShown: false},
  {colorName: 'Sienna', hexCode: '#A0522D', isShown: true},
  {colorName: 'Silver', hexCode: '#C0C0C0', isShown: false},
  {colorName: 'Sky Blue', hexCode: '#87CEEB', isShown: false},
  {colorName: 'Slate Blue', hexCode: '#6A5ACD', isShown: true},
  {colorName: 'Slate Gray', hexCode: '#708090', isShown: false},
  {colorName: 'Slate Grey', hexCode: '#708090', isShown: false},
  {colorName: 'Snow', hexCode: '#FFFAFA', isShown: false},
  {colorName: 'Spring Green', hexCode: '#00FF7F', isShown: false},
  {colorName: 'Steel Blue', hexCode: '#4682B4', isShown: true},
  {colorName: 'Tan', hexCode: '#D2B48C', isShown: false},
  {colorName: 'Teal', hexCode: '#008080', isShown: false},
  {colorName: 'Thistle', hexCode: '#D8BFD8', isShown: false},
  {colorName: 'Tomato', hexCode: '#FF6347', isShown: false},
  {colorName: 'Turquoise', hexCode: '#40E0D0', isShown: false},
  {colorName: 'Violet', hexCode: '#EE82EE', isShown: false},
  {colorName: 'Wheat', hexCode: '#F5DEB3', isShown: false},
  {colorName: 'White', hexCode: '#FFFFFF', isShown: false},
  {colorName: 'White Smoke', hexCode: '#F5F5F5', isShown: false},
  {colorName: 'Yellow', hexCode: '#FFFF00', isShown: false},
  {colorName: 'Yellow Green', hexCode: '#9ACD', isShown: false},
];
